### ISSUE TITLE
View crash in PyDev or other IDE

### ISSUE THREAD

**Issue by c1728p9** [elifiner/pydump#1]
Is it possible to load a dump in PyDev? If not are there any other IDEs that can be used to view the crash dumps?  Also, thanks for the awesome post-mortem debugging tool!

**Comment by finereli** [comment]
No, I don't think it's possible. In order to do that there will need to be some sort of support in the IDE itself, at least in the form of a menu item and a dialog.

What pydump does is simulate a traceback object with enough details for the command line debuggers to work with in their post_mortem call. There should be enough info there for an IDE debugger, but fitting that in sounds like a lot of work.

You can use https://pypi.python.org/pypi/pudb for a terminal approximation of an IDE debugger. That one is supported by pydump.

BTW, what are you using pydump for? You might have noticed, you're the first to ever report an issue and as far as I know the only other user of the lib besides me :).

**Comment by c1728p9** [comment]
I was thinking along the lines of loading it into PyDev with a script, rather that needing to go through a menu.  I was able to load it using load_dump and view the objects in PyDev, but I couldn't easily navigate the callstack, and it was hard to find local variables.  When I called debug_dump it would open pdb inside of PyDev.  Any ideas on how I could make it look like I was inside a callstack in python?

The program pudb sounds like it might be able to do what I need.  I'll give it a try.

I'm hoping to use it to track down hard to reproduce exceptions in the debugging tool pyOCD - https://github.com/mbedmicro/pyOCD.  Pydump seems like just what I need to do that.  I'm surprised more people aren't using your tool, as I haven't seen any other python crash dump tools.

**Comment by finereli** [comment]
I'm honored that you find this useful, thanks.

I'm not sure what kind of automation PyDev supports via scripts. The
debugger itself is written in Python (
https://github.com/fabioz/PyDev.Debugger). I started to look at how it's
post_mortem function can be hooked, but it looks like more effort than I
can invest right now. Let me know if you figure out a way.

**Comment by c1728p9** [comment]
I gave pudb a try, but it it looks like it is only for Mac and Linux computers (I'm running windows).  I opened a PyDev issue for supporting this: https://github.com/fabioz/PyDev.Debugger/issues/30 I'll let you know I make any progress on supporting this.  Thanks for the help.

**Comment by finereli** [comment]
Hey @c1728p9, did you have any luck with this? I think I'm going to close the issue - it's been a long time :).

**Comment by c1728p9** [comment]
Hi @elifiner, I haven't had any luck with this. Thanks for checking.
